### PR TITLE
use diffq-fixed

### PR DESCRIPTION
**Pull request by JackismyShephard**
Fixes https://github.com/nomadkaraoke/python-audio-separator/issues/149

@beveradb this should work but let me know if you experience any problems when building it on your end (especially on MacOS as I dont have access to that OS)

### CODE REVIEW

**Comment by beveradb** [comment]
Hey, sorry it took me so long to get around to testing this - have just been super busy with day job and family stuff so haven't had much free time for hobby code.

I support the approach you've taken here, as the original `diffq` [package seems to be archived](https://github.com/facebookresearch/diffq) so presumably is unsupported by facebook now.

Unfortunately though it doesn't build when I try to install `audio-separator` from your PR branch in a clean conda environment on my own mac:

```
pip install .
Processing /Users/andrew/Projects/python-audio-separator
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting beartype<0.19.0,>=0.18.5 (from audio-separator==0.24.1)
  Using cached beartype-0.18.5-py3-none-any.whl.metadata (30 kB)
Collecting diffq-fixed>=0.2 (from audio-separator==0.24.1)
  Downloading diffq_fixed-0.2.4.tar.gz (189 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [27 lines of output]
      Traceback (most recent call last):
        File "/Users/andrew/miniforge3/envs/audio-separator/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/andrew/miniforge3/envs/audio-separator/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/andrew/miniforge3/envs/audio-separator/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/rl/g00b5hr5191d9xx0zvss2pcr0000gp/T/pip-build-env-ff9cy1bc/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/rl/g00b5hr5191d9xx0zvss2pcr0000gp/T/pip-build-env-ff9cy1bc/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 304, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/rl/g00b5hr5191d9xx0zvss2pcr0000gp/T/pip-build-env-ff9cy1bc/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 522, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/private/var/folders/rl/g00b5hr5191d9xx0zvss2pcr0000gp/T/pip-build-env-ff9cy1bc/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 320, in run_setup
          exec(code, locals())
        File "<string>", line 48, in <module>
        File "/private/var/folders/rl/g00b5hr5191d9xx0zvss2pcr0000gp/T/pip-build-env-ff9cy1bc/overlay/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1010, in cythonize
          module_list, module_metadata = create_extension_list(
                                         ^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/rl/g00b5hr5191d9xx0zvss2pcr0000gp/T/pip-build-env-ff9cy1bc/overlay/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 845, in create_extension_list
          for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
        File "/private/var/folders/rl/g00b5hr5191d9xx0zvss2pcr0000gp/T/pip-build-env-ff9cy1bc/overlay/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 117, in nonempty
          raise ValueError(error_msg)
      ValueError: 'bitpack.pyx' doesn't match any files
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.
```

Perhaps you need to add wheels to your `diffq-fixed` package to cover the other operating systems which are provided by the diffq: https://pypi.org/project/diffq/#files

Or if this is a windows-only issue, perhaps we could do this in `pyproject.toml` instead?
```
diffq-fixed = { version = ">=0.2", platform = "win32" }
diffq = { version = ">=0.2", platform = "!=win32" }
```

**Comment by JackismyShephard** [comment]
This is indeed a windows only issues although I also think it would be nice to have wheels for python 3.12 on Linux.

I cannot really generate wheels for macos as I don't have a Mac available. I think conditionally using diffq-fixed on windows and Linux, as you suggest, is the way to go

**Comment by JackismyShephard** [comment]
This is indeed a windows only issues although I also think it would be nice to have wheels for python 3.12 on Linux.

I cannot really generate wheels for macos as I don't have a Mac available. I think conditionally using diffq-fixed on windows and Linux, as you suggest, is the way to go

You could also generate the macos wheels yourself if you.

**Comment by JackismyShephard** [comment]
You could also generate the macos wheels yourself if you want

**Comment by beveradb** [comment]
Hopefully this is fixed in `audio-separator` `0.24.3` and newer, as of commit https://github.com/nomadkaraoke/python-audio-separator/commit/af4e9e296cc871b120fdc8620d2ab9de291e5ec3

Ping me / repoen if not 😄

**Comment by JackismyShephard** [comment]
@beveradb Apologies for not getting back before now. I will try the latest version of `audio-separator` and let you know if the issue is fixed on windows 😄

**Pull request closed without merging**
