### PR TITLE
new models of various architectures

### PR DESCRIPTION
**Pull request by Eddycrack864**
# Models: 
### **MelBand Roformer Kim | FT by unwa**

Checkpoint Link: [ckpt](https://github.com/Eddycrack864/models_test/releases/download/model-configs/mel_band_roformer_kim_ft_unwa.ckpt)
Config Link: [config](https://github.com/Eddycrack864/models_test/releases/download/model-configs/config_mel_band_roformer_kim_ft_unwa.yaml)

### **MelBand Roformer | De-Reverb by anvuew**

Checkpoint Link: [ckpt](https://github.com/Eddycrack864/models_test/releases/download/model-configs/dereverb_mel_band_roformer_anvuew_sdr_19.1729.ckpt)
Config Link: [config](https://github.com/Eddycrack864/models_test/releases/download/model-configs/dereverb_mel_band_roformer_anvuew.yaml)

### **MelBand Roformer | De-Reverb Less Aggressive by anvuew**

Checkpoint Link: [ckpt](https://github.com/Eddycrack864/models_test/releases/download/model-configs/dereverb_mel_band_roformer_less_aggressive_anvuew_sdr_18.8050.ckpt)
Config Link: [config](https://github.com/Eddycrack864/models_test/releases/download/model-configs/dereverb_mel_band_roformer_anvuew.yaml)

### **MelBand Roformer | De-Reverb-Echo by Sucial**

Checkpoint Link: [ckpt](https://github.com/Eddycrack864/models_test/releases/download/model-configs/dereverb-echo_mel_band_roformer_sdr_10.0169.ckpt)
Config Link: [config](https://github.com/Eddycrack864/models_test/releases/download/model-configs/config_dereverb-echo_mel_band_roformer.yaml)

### **MelBand Roformer | De-Reverb-Echo V2 by Sucial**

Checkpoint Link: [ckpt](https://github.com/Eddycrack864/models_test/releases/download/model-configs/dereverb-echo_mel_band_roformer_sdr_13.4843_v2.ckpt)
Config Link: [config](https://github.com/Eddycrack864/models_test/releases/download/model-configs/config_dereverb-echo_mel_band_roformer_sdr_13.4843_v2.yaml)

### **MelBand Roformer Kim | SYHFT by SYH99999**

Checkpoint Link: [ckpt](https://github.com/Eddycrack864/models_test/releases/download/model-configs/MelBandRoformerSYHFT.ckpt)
Config Link: [config](https://github.com/Eddycrack864/models_test/releases/download/model-configs/config_vocals_mel_band_roformer_ft.yaml)

### **MelBand Roformer Kim | SYHFT V2 by SYH99999**

Checkpoint Link: [ckpt](https://github.com/Eddycrack864/models_test/releases/download/model-configs/MelBandRoformerSYHFTV2.ckpt)
Config Link: [config](https://github.com/Eddycrack864/models_test/releases/download/model-configs/config_vocals_mel_band_roformer_ft.yaml)

### **MelBand Roformer Kim | SYHFT V2.5 by SYH99999**

Checkpoint Link: [ckpt](https://github.com/Eddycrack864/models_test/releases/download/model-configs/MelBandRoformerSYHFTV2.5.ckpt)
Config Link: [config](https://github.com/Eddycrack864/models_test/releases/download/model-configs/config_vocals_mel_band_roformer_ft.yaml)

### **MelBand Roformer Kim | SYHFT V3 by SYH99999**

Checkpoint Link: [ckpt](https://github.com/Eddycrack864/models_test/releases/download/model-configs/MelBandRoformerSYHFTV3Epsilon.ckpt)
Config Link: [config](https://github.com/Eddycrack864/models_test/releases/download/model-configs/config_vocals_mel_band_roformer_ft.yaml)

### **MelBand Roformer Kim | Big SYHFT V1 by SYH99999**

Checkpoint Link: [ckpt](https://github.com/Eddycrack864/models_test/releases/download/model-configs/MelBandRoformerBigSYHFTV1.ckpt)
Config Link: [config](https://github.com/Eddycrack864/models_test/releases/download/model-configs/config_vocals_mel_band_roformer_big_v1_ft.yaml)

### **MelBand Roformer Kim | Big Beta 4 FT by unwa**

Checkpoint Link: [ckpt](https://github.com/Eddycrack864/models_test/releases/download/model-configs/melband_roformer_big_beta4.ckpt)
Config Link: [config](https://github.com/Eddycrack864/models_test/releases/download/model-configs/config_melbandroformer_big_beta4.yaml)

### **MelBand Roformer Kim | Big Beta 5e FT by unwa**

Checkpoint Link: [ckpt](https://github.com/Eddycrack864/models_test/releases/download/model-configs/melband_roformer_big_beta5e.ckpt)
Config Link: [config](https://github.com/Eddycrack864/models_test/releases/download/model-configs/config_melband_roformer_big_beta5e.yaml)

### **BS Roformer | Chorus Male-Female by Sucial**

Checkpoint Link: [ckpt](https://github.com/Eddycrack864/models_test/releases/download/model-configs/model_chorus_bs_roformer_ep_267_sdr_24.1275.ckpt)
Config Link: [config](https://github.com/Eddycrack864/models_test/releases/download/model-configs/config_chorus_male_female_bs_roformer.yaml)

### **MelBand Roformer | Aspiration by Sucial**

Checkpoint Link: [ckpt](https://github.com/Eddycrack864/models_test/releases/download/model-configs/aspiration_mel_band_roformer_sdr_18.9845.ckpt)
Config Link: [config](https://github.com/Eddycrack864/models_test/releases/download/model-configs/config_aspiration_mel_band_roformer.yaml)

### **MelBand Roformer | Aspiration Less Aggressive by Sucial**

Checkpoint Link: [ckpt](https://github.com/Eddycrack864/models_test/releases/download/model-configs/aspiration_mel_band_roformer_less_aggr_sdr_18.1201.ckpt)
Config Link: [config](https://github.com/Eddycrack864/models_test/releases/download/model-configs/config_aspiration_mel_band_roformer.yaml)

### **MelBand Roformer | Bleed Suppressor V1 by unwa & 97chris**

Checkpoint Link: [ckpt](https://github.com/Eddycrack864/models_test/releases/download/model-configs/mel_band_roformer_bleed_suppressor_v1.ckpt)
Config Link: [config](https://github.com/Eddycrack864/models_test/releases/download/model-configs/config_mel_band_roformer_bleed_suppressor_v1.yaml)

### **MDX23C De-Reverb by aufr33 & jarredou**

Checkpoint Link: [ckpt](https://github.com/Eddycrack864/models_test/releases/download/model-configs/MDX23C-De-Reverb-aufr33-jarredou.ckpt)
Config Link: [config](https://github.com/Eddycrack864/models_test/releases/download/model-configs/config_dereverb_mdx23c.yaml)

### **UVR-De-Reverb by aufr33 & jarredou**

Checkpoint Link: [pth](https://github.com/Eddycrack864/models_test/releases/download/model-configs/UVR-De-Reverb-aufr33-jarredou.pth)
JSON Config: (In PR)
Code to be added to [model_data_new.json](https://github.com/Eddycrack864/application_data/blob/main/vr_model_data/model_data_new.json) as i said in https://github.com/nomadkaraoke/python-audio-separator/issues/166#issuecomment-2543309965:
```
"97dc361a7a88b2c4542f68364b32c7f6": {
        "vr_model_param": "4band_v4_ms_fullband",
        "primary_stem": "Dry",
        "nout": 32,
        "nout_lstm": 128,
        "is_karaoke": false,
        "is_bv_model": false,
        "is_bv_model_rebalanced": 0.0
    }
```

## Another changes

I also renamed an existing model to give credit to its author.

_These models were tested on my Windows 11 with CPU end. If you find any error lmk as I may have made some oppsie._

### CODE REVIEW

**Comment by beveradb** [comment]
Wow, this is amazing thank you! I'm excited to test a few of these later on; I'll upload all of the files to the model configs release and merge this as soon as I'm at a faster internet connection 🙏

**Comment by beveradb** [comment]
Released in version `0.27` 🎉  

Now I'm definitely getting to the point where I feel we need to provide users of `audio-separator` with more info about the models to help know what different models do or how well they do it, as there's so much choice but very little info to help decide what to use...

Do you or @Bebra777228  happen to know if there's an easy way to find the [MVSEP leaderboard metrics](https://mvsep.com/quality_checker/multisong_leaderboard) (e.g. instrumental SDR, vocal SDR) for each of these models? 

If we could reliably map model filenames or add additional metadata to our [models.json](https://github.com/nomadkaraoke/python-audio-separator/blob/main/audio_separator/models.json) to enable querying those metrics from MVSEP for every supported model, it would be great to then list the SDR in the model list output (`audio-separator -l`) to help folks choose models which perform better for specific tasks!

**Comment by Bebra777228** [comment]
I will leave the question about requesting metrics from MVSEP to you, but there is a way to find the average SDR. Some models, when opened as an archive, contain a folder whose name sometimes includes the average SDR value, such as in the models `BS-Roformer-Viperx-1297` **(avg SDR: 12.9755)**, `Mel-Roformer-Viperx-1143` **(avg SDR: 11.4360)**, and other similar ones.

For example, for the model `MelBand Roformer Kim | FT by unwa`, you can see the value **`12.4604`**.

Screenshot:
image

I don't know if this will help in any way 🤷‍♂️

**Comment by Bebra777228** [comment]
The model MelBandRoformerSYHFTV2.5.ckpt was not loaded in model-configs.

**Comment by beveradb** [comment]
> The model MelBandRoformerSYHFTV2.5.ckpt was not loaded in model-configs.

What do you mean, sorry? 

Isn't this the file?
https://github.com/nomadkaraoke/python-audio-separator/releases/download/model-configs/config_vocals_mel_band_roformer_ft.yaml

**Comment by Bebra777228** [comment]
> > The model MelBandRoformerSYHFTV2.5.ckpt was not loaded in model-configs.
> 
> What do you mean, sorry?
> 
> Isn't this the file? https://github.com/nomadkaraoke/python-audio-separator/releases/download/model-configs/config_vocals_mel_band_roformer_ft.yaml

model - MelBandRoformerSYHFTV2.5.ckpt
config - config_vocals_mel_band_roformer_ft.yaml

MelBand Roformer Kim | SYHFT V2.5 by SYH99999
Checkpoint Link: [ckpt](https://github.com/Eddycrack864/models_test/releases/download/model-configs/MelBandRoformerSYHFTV2.5.ckpt)
Config Link: [config](https://github.com/Eddycrack864/models_test/releases/download/model-configs/config_vocals_mel_band_roformer_ft.yaml)

The model file is missing in model-configs.

**Comment by beveradb** [comment]
> The model file is missing in model-configs.

Sorry, I deleted my comment when I re-read your message and realized I'd missed the actual model (my brain first somehow interpreted "missed the model config file" which I checked and was there 😅 )

Uploaded the actual model file now; thanks for catching that!

**Comment by beveradb** [comment]
Apologies, the VR `UVR-De-Reverb-aufr33-jarredou.pth` one was also missing from the repo and missing config in `0.27.0`

I've just fixed it (among also implementing a model evaluation/scoring script which I intend to use to help folks choose better performing models more easily) in https://github.com/nomadkaraoke/python-audio-separator/pull/169/files

`audio-separator` release `0.27.1` 🤞

**Comment by Bebra777228** [comment]
I just decided to check the models again and it turns out that the MDX23C-De-Reverb-aufr33-jarredou.ckpt file is also missing:

MDX23C De-Reverb by aufr33 & jarredou
~Config Link: [config](https://github.com/Eddycrack864/models_test/releases/download/model-configs/config_dereverb_mdx23c.yaml)~

**Checkpoint Link: [ckpt](https://github.com/Eddycrack864/models_test/releases/download/model-configs/MDX23C-De-Reverb-aufr33-jarredou.ckpt)** ←

**Comment by beveradb** [comment]
Thanks, fixed!

**Pull request merged**
