### PR TITLE
Add output_bitrate argument.

### PR DESCRIPTION
**Pull request by empz**
Adds output_bitrate parameter to set the bitrate of the outputs. Defaults to 320k for mp3 if not set.

### CODE REVIEW

**Comment by beveradb** [comment]
Thank you! I'll test and merge when I'm home later today ☺️

**Comment by empz** [comment]
> Thank you! I'll test and merge when I'm home later today ☺️

Sorry to insist but could this get merged soon?  Thanks 🙏

**Comment by beveradb** [comment]
Sure, I should get to testing it today; I just landed in London (8 hour flight), apologies for the slow response.
Curious what the urgency is though, can't you just use it from your own branch until I merge and cut a release?

**Comment by empz** [comment]
> Sure, I should get to testing it today; I just landed in London (8 hour flight), apologies for the slow response. Curious what the urgency is though, can't you just use it from your own branch until I merge and cut a release?

I'm using it inside a docker image running in the cloud, so using my own branch would require to publish my own version of the package to PyPi. I'll just want, no rush!

**Comment by beveradb** [comment]
Tested and working with variety of formats and bitrates, with sane defaults. Thank you! 🙇

**Comment by beveradb** [comment]
This is now released in `audio-separator` versions greater than `0.19.0` 🎉

**Pull request merged**
