### PR TITLE
Activate torch.cuda.amp.autocast() for roformer inference

### PR DESCRIPTION
**Pull request by ntamotsu**
* [`audio_separator/separator/architectures/mdxc_separator.py`](diffhunk://#diff-a3e54b02e2437c945d0c4e9e2e7a6b730d056292cfea15235eedddd1c1f64090L242-R242): Re-enabled the `torch.cuda.amp.autocast()` context manager in the `demix` method to improve performance by using automatic mixed precision.

If there are any specific reasons to keep it commented out, feel free to close this. However, enabling this can improve the speed by 1.5 to 2 times, for example, for the MelBand-Karaoke model, so we would prefer to keep it enabled if possible.

### CODE REVIEW

**Comment by beveradb** [comment]
Hey, thanks for raising this PR!
I got excited about a potential 2x speedup, but when I tested on my own machine I get the same inference time but get this warning:
`/Users/andrew/miniforge3/envs/audio-separator-clean-py311/lib/python3.11/site-packages/torch/amp/autocast_mode.py:250: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling`

I assume this needs tidying up to only try to reference CUDA if CUDA is available?

Cheers,
Andrew

**Comment by ntamotsu** [comment]
Thank you for your feedback, Andrew. I've expanded the use of autocast to all models and made some adjustments to address the issues you mentioned. Here's a summary of the changes, test results, and additional considerations:

## Changes Made

* `README.md`: Updated usage instructions and added a description for the new `--use_autocast` parameter.
* `audio_separator/separator/separator.py`: 
  * Added `use_autocast` attribute to the `Separator` class and its initialization method.
  * Implemented logic to check and use autocast during the separation process.
* `audio_separator/utils/cli.py`: Added `--use_autocast` argument to the CLI and passed it to the `Separator` class.
* `tests/unit/test_cli.py`: Added a unit test for the `use_autocast` argument.
* `poetry.lock`: Updated PyTorch dependency to version 2.4 to utilize the newly introduced `is_autocast_available()` function.

## Inference Time Test Results

I've conducted extensive tests across various models and hardware configurations. The results show that inference speed improved 1-2 times for most models when using autocast on GPU. However, the results vary for CPU and Apple Silicon. Here are the key findings:

1. GPU (Colab T4): Significant speedup observed for most models.
2. CPU: Autocast caused issues with some models, resulting in no progress or runtime errors.
3. Apple Silicon (M1 Mac): No significant difference observed with autocast.

●Colab T4 (audio file length=03m59s) 

model | use_autocast? | other config | separation duration (average of 3 measurements)
-- | -- | -- | --
mel_band_roformer_karaoke_aufr33_viperx_sdr_10.1956.ckpt | True | --output_format=WAV --mdxc_segment_size=1101 --mdxc_override_model_segment_size --mdxc_overlap=2 | 01m29s
  | False |   | 03m34s
UVR-DeEcho-DeReverb.pth | True | --output_format=WAV --vr_window_size=320 --vr_aggression=50 --vr_enable_tta | 00m54s
  | False |   | 01m02s
htdemucs.yaml | True | --output_format=WAV | 00m22s
  | False |   | 00m33s
UVR_MDXNET_KARA_2.onnx | True | --output_format=WAV | 00m26s
  | False |   | 00m27s
MDX23C_D1581.ckpt | True | --output_format=WAV | 00m32s
  | False |   | 01m11s

●Colab CPU (audio file length=00m02s)

model | use_autocast? | other config | separation duration (average of 3 measurements)
-- | -- | -- | --
mel_band_roformer_karaoke_aufr33_viperx_sdr_10.1956.ckpt | True | --output_format=WAV --mdxc_segment_size=1101 --mdxc_override_model_segment_size --mdxc_overlap=2 | ∞ (tqdm shows no progress)
  | False |   | (RuntimeError)
UVR-DeEcho-DeReverb.pth | True | --output_format=WAV --vr_window_size=320 --vr_aggression=50 --vr_enable_tta | (RuntimeError)
  | False |   | 00m31s
htdemucs.yaml | True | --output_format=WAV | ∞ (tqdm shows no progress)
  | False |   | 00m53s
UVR_MDXNET_KARA_2.onnx | True | --output_format=WAV | 00m23s
  | False |   | 00m20s
MDX23C_D1581.ckpt | True | --output_format=WAV | ∞ (tqdm shows no progress)
  | False |   | 06m43s

●M1 Mac (audio file length=01m30s)

model | use_autocast? | other config | separation duration (average of 3 measurements)
-- | -- | -- | --
mel_band_roformer_karaoke_aufr33_viperx_sdr_10.1956.ckpt | True | --output_format=WAV --mdxc_segment_size=1101 --mdxc_override_model_segment_size --mdxc_overlap=2 | 08m05s
  | False |   | 08m04s
UVR-DeEcho-DeReverb.pth | True | --vr_window_size=320 --vr_aggression=50 --vr_enable_tta | 00m41s
  | False |   | 00m42s
htdemucs.yaml | True | --output_format=WAV | 00m31s
  | False |   | 00m31s
UVR_MDXNET_KARA_2.onnx | True | --output_format=WAV | 00m16s
  | False |   | 00m16s
MDX23C_D1581.ckpt | True | --output_format=WAV | 01m37s
  | False |   | 01m38s

## Additional Considerations

* Due to the issues observed with CPU inference when using autocast (no progress or errors for some models), we've set `--use_autocast` to False by default. This ensures compatibility across different hardware configurations out of the box.
* Regarding Apple Silicon, the lack of performance improvement is due to the current absence of MPS support for autocast. However, we expect this to be supported in the future. In fact, looking at the PyTorch 2.5 source code, it appears that MPS support is being implemented. Once this support is available, we anticipate performance improvements for Apple Silicon users as well.

These changes and considerations should provide a more robust and future-proof implementation of autocast in our project. Users can now benefit from the performance improvements on supported hardware while maintaining compatibility across different systems.

**Comment by beveradb** [comment]
Nice work, thank you! 
I'll test and merge tomorrow when I have time 🙏

**Comment by beveradb** [comment]
Tested and merged, should be live from the latest audio-separator release: `0.22.0`

Thanks again for your contribution!

**Pull request merged**
